-- AlterTable
ALTER TABLE "Program" ALTER COLUMN "endTime" DROP DEFAULT,
ALTER COLUMN "endTime" SET DATA TYPE TEXT,
ALTER COLUMN "startTime" DROP DEFAULT,
ALTER COLUMN "startTime" SET DATA TYPE TEXT;
