import { useEffect, useState } from "react";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Link, useLocation } from "wouter";
import { ArrowLeft, ArrowRight, CalendarDays, Clock3, GraduationCap, Plus, Settings2, X } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { academicYearErrorMessage, dateOnly, useAcademicYear, useAcademicYears, useSaveAcademicYear, type AcademicYear, type CreateAcademicYearRequest } from "@/lib/academic-years-api";
import { academicCalendarErrorMessage, useAcademicCalendar, useAcademicCalendarRecord, useDeleteAcademicCalendar, useSaveAcademicCalendar, type CreateAcademicCalendarRequest, type DayType, type UpdateAcademicCalendarRequest } from "@/lib/academic-calendar-api";
import { programErrorMessage, toProgramViewModel, toWeekdayCodes, type ProgramRequest, type ProgramUpdateRequest, useProgram, usePrograms, useSaveProgram } from "@/lib/programs-api";
import { classErrorMessage, useClass, useClasses, useSaveClass, type ClassCreateRequest, type ClassUpdateRequest } from "@/lib/classes-api";
import { sectionErrorMessage, useSaveSection, useSections, useSectionsByClass, type SectionCreateRequest, type SectionUpdateRequest } from "@/lib/sections-api";
import { subjectErrorMessage, useDeleteSubject, useSaveSubject, useSubject, useSubjectsByClass, type SubjectCreateRequest, type SubjectUpdateRequest } from "@/lib/subjects-api";
import { type Permission, type User, hasPermission, useItem, useResource, useSaveResource } from "@/lib/mock-erp";
import { AccessState, AppButton, Empty, Loading, PageHeader, SearchBox, SelectBox, Status, date, titleCase } from "@/pages/page-primitives";
export type SetupResource = "academicYears" | "programs" | "classes" | "sections";
const setupMeta: Record<SetupResource, { title: string; singular: string; read: Permission; create: Permission; update: Permission }> = {
  academicYears: { title: "Academic Years", singular: "academic year", read: "CLASS_READ", create: "CLASS_CREATE", update: "CLASS_UPDATE" },
  programs: { title: "Programs & Shifts", singular: "program / shift", read: "SHIFT_READ", create: "SHIFT_CREATE", update: "SHIFT_UPDATE" },
  classes: { title: "Classes", singular: "class", read: "CLASS_READ", create: "CLASS_CREATE", update: "CLASS_UPDATE" },
  sections: { title: "Sections", singular: "section", read: "CLASS_READ", create: "CLASS_CREATE", update: "CLASS_UPDATE" },
};
const setupSchema = {
  academicYears: z.object({ schoolId: z.string().min(2, "School ID is required"), name: z.string().min(3, "Name is required"), startDate: z.string().min(8, "Start date is required"), endDate: z.string().min(8, "End date is required") }),
  programs: z.object({ name: z.string().min(2, "Name is required"), academicYearId: z.string().min(1, "Choose an academic year"), primary: z.string(), daysOfWeek: z.string().min(3, "Add at least one day"), startTime: z.string().min(4, "Start time is required"), endTime: z.string().min(4, "End time is required") }),
  classes: z.object({ name: z.string().min(2, "Name is required"), programId: z.string().min(1, "Choose a program or shift") }),
  sections: z.object({ name: z.string().min(1, "Name is required"), classId: z.string().min(1, "Choose a class") }),
};

const academicYearSchema = z.object({
  schoolId: z.string().min(2, "School ID is required"),
  name: z.string().min(3, "Name is required"),
  startDate: z.string().min(10, "Start date is required"),
  endDate: z.string().min(10, "End date is required"),
}).refine((value) => value.startDate < value.endDate, {
  path: ["endDate"],
  message: "Start date must be before end date.",
});

export function AcademicYearsList() {
  const query = useAcademicYears(); const [search, setSearch] = useState(""); const [, setLocation] = useLocation();
  if (query.isLoading) return <><PageHeader title="Academic Years" /><Loading /></>;
  if (query.isError) return <><PageHeader title="Academic Years" /><Empty title="Could not load academic years" detail={academicYearErrorMessage(query.error, "Please try again later.")} action={<AppButton onClick={() => query.refetch()}>Try again</AppButton>} /></>;
  const rows = (query.data || []).filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader eyebrow="Academic hierarchy" title="Academic Years" description="Start at the academic cycle, then connect programmes, classes, and sections." action={<AppButton onClick={() => setLocation("/academic-years/new")}><Plus size={16} />Add academic year</AppButton>} /><div className="hierarchy-banner"><span className="hierarchy-node">Academic Year</span><ArrowRight size={14} /><span className="hierarchy-node">Program / Shift</span><ArrowRight size={14} /><span className="hierarchy-node">Class</span><ArrowRight size={14} /><span className="hierarchy-node">Section</span></div><div className="list-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search academic years" /></div>{rows.length === 0 ? <Empty title="No academic years found" detail="Add the first record to establish this layer of the academic hierarchy." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Year</th><th>School ID</th><th>Starts</th><th>Ends</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/academic-years/${row.id}`} className="table-link"><strong>{row.name}</strong></Link></td><td>{row.schoolId}</td><td>{date(row.startDate)}</td><td>{date(row.endDate)}</td><td className="row-actions"><Link href={`/academic-years/${row.id}/edit`} className="icon-button" title="Edit academic year"><Settings2 size={15} /></Link></td></tr>)}</tbody></table></div><div className="table-foot"><span>{rows.length} records</span><span className="table-foot-note">No delete action is available for academic setup records</span></div></div>}</>;
}

export function AcademicYearForm({ id }: { id?: string }) {
  const editing = Boolean(id); const query = useAcademicYear(id); const save = useSaveAcademicYear(id); const [, setLocation] = useLocation();
  const form = useForm<Record<string, unknown>>({ resolver: zodResolver(academicYearSchema), defaultValues: { schoolId: "NAC-BLR", name: "2026–27", startDate: "2026-06-01", endDate: "2027-05-31" } });
  useEffect(() => { if (query.data) form.reset({ schoolId: query.data.schoolId, name: query.data.name, startDate: dateOnly(query.data.startDate), endDate: dateOnly(query.data.endDate) }); }, [query.data]);
  if (editing && query.isLoading) return <Loading />;
  if (editing && query.isError) return <Empty title="Could not load academic year" detail={academicYearErrorMessage(query.error, "Please try again later.")} />;
  if (editing && !query.data) return <Empty title="Record not found" detail="This academic year is no longer available." />;
  const submit = (values: CreateAcademicYearRequest) => {
    const typed = values as unknown as CreateAcademicYearRequest;
    const payload = editing ? { name: typed.name, startDate: typed.startDate, endDate: typed.endDate } : typed;
    save.mutate(payload, { onSuccess: (saved) => { toast({ title: editing ? "Academic year updated" : "Academic year created" }); setLocation(`/academic-years/${saved.id}`); }, onError: (error) => toast({ title: "Could not save academic year", description: academicYearErrorMessage(error, "Please check the form and try again.") }) });
  };
  return <><button className="back-link page-back" onClick={() => setLocation("/academic-years")}><ArrowLeft size={15} />Back to Academic Years</button><PageHeader eyebrow={editing ? "Edit academic setup" : "New academic setup"} title={editing ? "Edit academic year" : "Add academic year"} description="Keep each academic cycle connected to its school." /><form className="form-card" onSubmit={form.handleSubmit((values) => submit(values), () => toast({ title: "Check the form", description: "A few required fields still need your attention." }))}><div className="form-grid"><Field form={form} name="schoolId" label="School ID" disabled={editing} />{editing && <p className="field-help">School ID cannot be changed after creation.</p>}<Field form={form} name="name" label="Academic year name" /><Field form={form} name="startDate" label="Start date" type="date" /><Field form={form} name="endDate" label="End date" type="date" /></div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation("/academic-years")}>Cancel</AppButton><AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create academic year"}<ArrowRight size={16} /></AppButton></div></form></>;
}

export function AcademicYearDetail({ id }: { id: string }) {
  const query = useAcademicYear(id); const [, setLocation] = useLocation();
  if (query.isLoading) return <Loading />;
  if (query.isError) return <Empty title="Could not load academic year" detail={academicYearErrorMessage(query.error, "Please try again later.")} />;
  const item = query.data;
  if (!item) return <Empty title="Record not found" detail="This academic year may no longer be available." action={<Link href="/academic-years" className="text-button">Back to Academic Years</Link>} />;
  return <><button className="back-link page-back" onClick={() => setLocation("/academic-years")}><ArrowLeft size={15} />Back to Academic Years</button><div className="detail-header"><div className="detail-title"><div className="hierarchy-emblem"><GraduationCap size={25} /></div><div><div className="eyebrow">Academic hierarchy</div><h1>{item.name}</h1><p>{item.schoolId} · {date(item.startDate)} to {date(item.endDate)}</p></div></div><Link href={`/academic-years/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-semibold"><Settings2 size={15} />Edit</Link></div><div className="detail-grid"><section className="panel detail-panel"><div className="panel-head"><div><div className="eyebrow">Connected record</div><h2>Academic Year</h2></div></div><div className="detail-fields"><div className="detail-field"><span>School ID</span><strong>{item.schoolId}</strong></div><div className="detail-field"><span>Name</span><strong>{item.name}</strong></div><div className="detail-field"><span>Start date</span><strong>{date(item.startDate)}</strong></div><div className="detail-field"><span>End date</span><strong>{date(item.endDate)}</strong></div></div></section></div></>;
}

const dayTypeLabels: Record<DayType, string> = { WORKING_DAY: "Working day", WEEKEND: "Weekend", HOLIDAY: "Holiday", SPECIAL_WORKING_DAY: "Special working day" };
const dayTypeOptions: [DayType, string][] = Object.entries(dayTypeLabels) as [DayType, string][];
const calendarSchema = z.object({
  academicYearId: z.string().min(1, "Choose an academic year"),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Date is required"),
  dayType: z.enum(["WORKING_DAY", "WEEKEND", "HOLIDAY", "SPECIAL_WORKING_DAY"]),
  title: z.string().min(2, "Title is required"),
  description: z.string().optional(),
  isWorkingDay: z.string(),
});
const calendarFilterSchema = { dayType: ["All", "Working day", "Weekend", "Holiday", "Special working day"], working: ["All", "Working", "Non-working"] };
const calendarDateValue = (value?: string) => value ? value.slice(0, 10) : "";
const dayTypeFromLabel = (value: string): DayType | undefined => dayTypeOptions.find(([, label]) => label === value)?.[0];

export function AcademicCalendarList({ session }: { session: User }) {
  const years = useAcademicYears(); const [academicYearId, setAcademicYearId] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [dayType, setDayType] = useState("All"); const [working, setWorking] = useState("All"); const [, setLocation] = useLocation();
  const query = useAcademicCalendar({ academicYearId: academicYearId || undefined, from: from || undefined, to: to || undefined, dayType: dayTypeFromLabel(dayType), isWorkingDay: working === "All" ? undefined : working === "Working" });
  if (query.isLoading || years.isLoading) return <><PageHeader title="Academic Calendar" /><Loading /></>;
  if (query.isError || years.isError) return <><PageHeader title="Academic Calendar" /><Empty title="Could not load academic calendar" detail={academicCalendarErrorMessage(query.error || years.error, "The academic calendar service is unavailable.")} action={<AppButton onClick={() => { query.refetch(); years.refetch(); }}>Try again</AppButton>} /></>;
  const yearNames = new Map((years.data || []).map((year) => [year.id, year.name]));
  const rows = query.data || [];
  return <><PageHeader eyebrow="Academic operations" title="Academic Calendar" description="Manage working days, weekends, holidays, and special working days for an academic year." action={hasPermission(session.role, "SHIFT_CREATE") && <AppButton onClick={() => setLocation("/academic-calendar/new")}><Plus size={16} />Add calendar record</AppButton>} /><div className="list-toolbar"><label className="field"><span>Academic year</span><select value={academicYearId} onChange={(event) => setAcademicYearId(event.target.value)}><option value="">All academic years</option>{(years.data || []).map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</select></label><div className="toolbar-right"><label className="field"><span>From</span><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="field"><span>To</span><input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><SelectBox value={dayType} onChange={setDayType} label="Type" options={calendarFilterSchema.dayType.slice(1)} /><SelectBox value={working} onChange={setWorking} label="Working" options={calendarFilterSchema.working.slice(1)} /></div></div>{rows.length === 0 ? <Empty title="No calendar records found" detail="Create records manually or seed an academic year from the backend when a seed workflow is approved." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Date</th><th>Academic year</th><th>Type</th><th>Title</th><th>Working day</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/academic-calendar/${row.id}`} className="table-link"><strong>{date(calendarDateValue(row.date))}</strong></Link></td><td>{yearNames.get(row.academicYearId) || row.academicYearId}</td><td><Status>{dayTypeLabels[row.dayType]}</Status></td><td>{row.title}</td><td>{row.isWorkingDay ? "Yes" : "No"}</td><td className="row-actions">{hasPermission(session.role, "SHIFT_UPDATE") && <Link href={`/academic-calendar/${row.id}/edit`} className="icon-button" title="Edit calendar record"><Settings2 size={15} /></Link>}</td></tr>)}</tbody></table></div><div className="table-foot"><span>{rows.length} records</span><span className="table-foot-note">Calendar records are Academic Year scoped</span></div></div>}</>;
}

export function AcademicCalendarForm({ id }: { id?: string }) {
  const editing = Boolean(id); const query = useAcademicCalendarRecord(id); const years = useAcademicYears(); const save = useSaveAcademicCalendar(id); const [, setLocation] = useLocation();
  const form = useForm<Record<string, unknown>>({ resolver: zodResolver(calendarSchema), defaultValues: { academicYearId: "", date: new Date().toISOString().slice(0, 10), dayType: "WORKING_DAY", title: "Working Day", description: "", isWorkingDay: "true" } });
  useEffect(() => { if (query.data) form.reset({ academicYearId: query.data.academicYearId, date: calendarDateValue(query.data.date), dayType: query.data.dayType, title: query.data.title, description: query.data.description || "", isWorkingDay: String(query.data.isWorkingDay) }); }, [query.data]);
  if (editing && (query.isLoading || years.isLoading)) return <Loading />;
  if (years.isError) return <Empty title="Could not load academic years" detail={academicCalendarErrorMessage(years.error, "Academic years are required for calendar records.")} />;
  if (editing && query.isError) return <Empty title="Could not load calendar record" detail={academicCalendarErrorMessage(query.error, "The requested calendar record could not be loaded.")} />;
  if (editing && !query.data) return <Empty title="Calendar record not found" detail="This calendar record may no longer be available." />;
  const submit = (values: Record<string, unknown>) => {
    const common = { date: String(values.date), dayType: values.dayType as DayType, title: String(values.title), description: String(values.description || ""), isWorkingDay: values.isWorkingDay === "true" };
    const payload: CreateAcademicCalendarRequest | UpdateAcademicCalendarRequest = editing ? common : { ...common, academicYearId: String(values.academicYearId) };
    save.mutate(payload, { onSuccess: (saved) => { toast({ title: editing ? "Calendar record updated" : "Calendar record created" }); setLocation(`/academic-calendar/${saved.id}`); }, onError: (error) => toast({ title: "Could not save calendar record", description: academicCalendarErrorMessage(error, "Please check the form and try again.") }) });
  };
  return <><button className="back-link page-back" onClick={() => setLocation("/academic-calendar")}><ArrowLeft size={15} />Back to Academic Calendar</button><PageHeader eyebrow={editing ? "Edit calendar" : "New calendar record"} title={editing ? "Edit calendar record" : "Add calendar record"} description="Create date-specific working day, weekend, holiday, or special working day records." /><form className="form-card" onSubmit={form.handleSubmit((values) => submit(values), () => toast({ title: "Check the form", description: "A few required fields still need your attention." }))}><div className="form-grid"><SelectField form={form} name="academicYearId" label="Academic year" disabled={editing} options={(years.data || []).map((year) => [year.id, year.name])} />{editing && <p className="field-help">Academic year cannot be changed during calendar editing.</p>}<Field form={form} name="date" label="Date" type="date" /><SelectField form={form} name="dayType" label="Day type" options={dayTypeOptions} /><Field form={form} name="title" label="Title" /><SelectField form={form} name="isWorkingDay" label="Working day" options={[["true", "Yes"], ["false", "No"]]} /><div className="field field-wide"><label htmlFor="calendar-description">Description</label><textarea id="calendar-description" rows={4} {...form.register("description")} /></div></div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation("/academic-calendar")}>Cancel</AppButton><AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create calendar record"}<ArrowRight size={16} /></AppButton></div></form></>;
}

export function AcademicCalendarDetail({ id, session }: { id: string; session: User }) {
  const query = useAcademicCalendarRecord(id); const years = useAcademicYears(); const remove = useDeleteAcademicCalendar(); const [, setLocation] = useLocation();
  if (query.isLoading || years.isLoading) return <Loading />;
  if (query.isError || years.isError) return <Empty title="Could not load calendar record" detail={academicCalendarErrorMessage(query.error || years.error, "The requested calendar record could not be loaded.")} action={<Link href="/academic-calendar" className="text-button">Back to Academic Calendar</Link>} />;
  const item = query.data;
  if (!item) return <Empty title="Calendar record not found" detail="This calendar record may no longer be available." action={<Link href="/academic-calendar" className="text-button">Back to Academic Calendar</Link>} />;
  const academicYear = (years.data || []).find((year) => year.id === item.academicYearId);
  const deleteRecord = () => { if (!window.confirm("Soft-delete this academic calendar record? Attendance checks will no longer see it in normal reads.")) return; remove.mutate(id, { onSuccess: () => { toast({ title: "Calendar record deleted" }); setLocation("/academic-calendar"); }, onError: (error) => toast({ title: "Could not delete calendar record", description: academicCalendarErrorMessage(error, "Please try again.") }) }); };
  return <><button className="back-link page-back" onClick={() => setLocation("/academic-calendar")}><ArrowLeft size={15} />Back to Academic Calendar</button><div className="detail-header"><div className="detail-title"><div className="hierarchy-emblem"><CalendarDays size={25} /></div><div><div className="eyebrow">Academic Calendar</div><h1>{item.title}</h1><p>{date(calendarDateValue(item.date))} · {academicYear?.name || item.academicYearId}</p></div></div><div className="detail-actions">{hasPermission(session.role, "SHIFT_UPDATE") && <Link href={`/academic-calendar/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-semibold"><Settings2 size={15} />Edit</Link>}{hasPermission(session.role, "SHIFT_UPDATE") && <AppButton variant="danger" onClick={deleteRecord} disabled={remove.isPending}><X size={15} />Delete</AppButton>}</div></div><div className="detail-grid"><section className="panel detail-panel"><div className="panel-head"><div><div className="eyebrow">Calendar record</div><h2>{dayTypeLabels[item.dayType]}</h2></div><Status>{item.isWorkingDay ? "Active" : "Pending"}</Status></div><div className="detail-fields">{[["Academic year", academicYear?.name || item.academicYearId], ["Date", date(calendarDateValue(item.date))], ["Day type", dayTypeLabels[item.dayType]], ["Working day", item.isWorkingDay ? "Yes" : "No"], ["Description", item.description || "—"], ["Created", date(calendarDateValue(item.createdAt))], ["Updated", date(calendarDateValue(item.updatedAt))]].map(([label, value]) => <div className="detail-field" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section></div></>;
}

const programSchema = z.object({
  name: z.string().min(2, "Name is required"),
  academicYearId: z.string().min(1, "Choose an academic year"),
  primary: z.string(),
  daysOfWeek: z.string().min(3, "Add at least one day"),
  startTime: z.string().min(5, "Start time is required"),
  endTime: z.string().min(5, "End time is required"),
}).refine((value) => value.startTime < value.endTime, { path: ["endTime"], message: "Start time must be before end time." }).refine((value) => {
  const values = value.daysOfWeek.split(",").map((day) => day.trim()).filter(Boolean);
  return values.length > 0 && toWeekdayCodes(value.daysOfWeek).length === values.length;
}, { path: ["daysOfWeek"], message: "Use valid weekday names separated by commas." });

export function ProgramsList() {
  const query = usePrograms(); const years = useAcademicYears(); const [search, setSearch] = useState(""); const [, setLocation] = useLocation();
  if (query.isLoading || years.isLoading) return <><PageHeader title="Programs & Shifts" /><Loading /></>;
  if (query.isError || years.isError) return <><PageHeader title="Programs & Shifts" /><Empty title="Could not load academic programs" detail={programErrorMessage(query.error || years.error, "Could not load academic programs.")} action={<AppButton onClick={() => { query.refetch(); years.refetch(); }}>Try again</AppButton>} /></>;
  const yearNames = new Map((years.data || []).map((year) => [year.id, year.name]));
  const rows = (query.data || []).map((program) => toProgramViewModel(program, yearNames.get(program.academicYearId))).filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader eyebrow="Academic hierarchy" title="Programs & Shifts" description="The programme and shift layer underneath each academic year." action={<AppButton onClick={() => setLocation("/academic-programs/new")}><Plus size={16} />Add program / shift</AppButton>} /><div className="hierarchy-banner"><span className="hierarchy-node">Academic Year</span><ArrowRight size={14} /><span className="hierarchy-node">Program / Shift</span><ArrowRight size={14} /><span className="hierarchy-node">Class</span><ArrowRight size={14} /><span className="hierarchy-node">Section</span></div><div className="list-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search programs & shifts" /></div>{rows.length === 0 ? <Empty title="No programs & shifts found" detail="Add the first program to establish this layer of the academic hierarchy." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Programme / shift</th><th>Academic year</th><th>Primary</th><th>Days</th><th>Start</th><th>End</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/academic-programs/${row.id}`} className="table-link"><strong>{row.name}</strong></Link></td><td>{row.academicYear}</td><td><Status>{row.primary ? "Active" : "Pending"}</Status></td><td>{row.daysOfWeek.join(" · ")}</td><td>{row.startTime}</td><td>{row.endTime}</td><td className="row-actions"><Link href={`/academic-programs/${row.id}/edit`} className="icon-button" title="Edit program"><Settings2 size={15} /></Link></td></tr>)}</tbody></table></div><div className="table-foot"><span>{rows.length} records</span><span className="table-foot-note">No delete action is available for academic setup records</span></div></div>}</>;
}

export function ProgramForm({ id }: { id?: string }) {
  const editing = Boolean(id); const query = useProgram(id); const years = useAcademicYears(); const save = useSaveProgram(id); const [, setLocation] = useLocation();
  const form = useForm<Record<string, unknown>>({ resolver: zodResolver(programSchema), defaultValues: { name: "Regular Day Programme", academicYearId: "", primary: "true", daysOfWeek: "Monday, Tuesday, Wednesday, Thursday, Friday", startTime: "09:00", endTime: "16:00" } });
  useEffect(() => { if (query.data) form.reset({ name: query.data.name, academicYearId: query.data.academicYearId, primary: String(query.data.isPrimary), daysOfWeek: toProgramViewModel(query.data).daysOfWeek.join(", "), startTime: query.data.startTime, endTime: query.data.endTime }); }, [query.data]);
  if (editing && (query.isLoading || years.isLoading)) return <Loading />;
  if (years.isError) return <Empty title="Could not load academic years" detail={programErrorMessage(years.error, "Could not load academic programs.")} />;
  if (editing && query.isError) return <Empty title="Could not load academic program" detail={programErrorMessage(query.error, "Could not load academic program.")} />;
  if (editing && !query.data) return <Empty title="Record not found" detail="This academic program is no longer available." />;
  const submit = (values: Record<string, unknown>) => {
    const name = String(values.name); const daysOfWeek = toWeekdayCodes(String(values.daysOfWeek));
    const common = { name, isPrimary: values.primary === "true", daysOfWeek, startTime: String(values.startTime), endTime: String(values.endTime) };
    const payload: ProgramRequest | ProgramUpdateRequest = editing ? common : { ...common, academicYear: String(values.academicYearId) };
    save.mutate(payload, { onSuccess: (saved) => { toast({ title: editing ? "Program updated" : "Program created" }); setLocation(`/academic-programs/${saved.id}`); }, onError: (error) => toast({ title: "Could not save academic program", description: programErrorMessage(error, "Could not save academic program.") }) });
  };
  return <><button className="back-link page-back" onClick={() => setLocation("/academic-programs")}><ArrowLeft size={15} />Back to Programs & Shifts</button><PageHeader eyebrow={editing ? "Edit academic setup" : "New academic setup"} title={editing ? "Edit program / shift" : "Add program / shift"} description="Keep each programme connected to its academic year." /><form className="form-card" onSubmit={form.handleSubmit((values) => submit(values), () => toast({ title: "Check the form", description: "A few required fields still need your attention." }))}><div className="form-grid"><Field form={form} name="name" label="Programme / shift name" /><SelectField form={form} name="academicYearId" label="Academic year" disabled={editing} options={(years.data || []).map((year) => [year.id, year.name])} />{editing && <p className="field-help">Academic year cannot be changed during program editing.</p>}<SelectField form={form} name="primary" label="Primary programme" options={[["true", "Primary"], ["false", "Non-primary"]]} /><Field form={form} name="daysOfWeek" label="Days of week" /><Field form={form} name="startTime" label="Start time" type="time" /><Field form={form} name="endTime" label="End time" type="time" /></div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation("/academic-programs")}>Cancel</AppButton><AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create program / shift"}<ArrowRight size={16} /></AppButton></div></form></>;
}

export function ProgramDetail({ id }: { id: string }) {
  const query = useProgram(id); const years = useAcademicYears(); const [, setLocation] = useLocation();
  if (query.isLoading || years.isLoading) return <Loading />;
  if (query.isError || years.isError) return <Empty title="Could not load academic program" detail={programErrorMessage(query.error || years.error, "Could not load academic program.")} />;
  const item = query.data;
  if (!item) return <Empty title="Record not found" detail="This academic program may no longer be available." action={<Link href="/academic-programs" className="text-button">Back to Programs & Shifts</Link>} />;
  const view = toProgramViewModel(item, (years.data || []).find((year) => year.id === item.academicYearId)?.name);
  return <><button className="back-link page-back" onClick={() => setLocation("/academic-programs")}><ArrowLeft size={15} />Back to Programs & Shifts</button><div className="detail-header"><div className="detail-title"><div className="hierarchy-emblem"><Clock3 size={25} /></div><div><div className="eyebrow">Academic hierarchy</div><h1>{view.name}</h1><p>{view.academicYear} · {view.primary ? "Primary" : "Non-primary"}</p></div></div><Link href={`/academic-programs/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-semibold"><Settings2 size={15} />Edit</Link></div><div className="detail-grid"><section className="panel detail-panel"><div className="panel-head"><div><div className="eyebrow">Connected record</div><h2>Program / shift</h2></div><Status>{view.primary ? "Active" : "Pending"}</Status></div><div className="detail-fields"><div className="detail-field"><span>Academic year</span><strong>{view.academicYear}</strong></div><div className="detail-field"><span>Primary</span><strong>{view.primary ? "Yes" : "No"}</strong></div><div className="detail-field"><span>Days</span><strong>{view.daysOfWeek.join(" · ")}</strong></div><div className="detail-field"><span>Start time</span><strong>{view.startTime}</strong></div><div className="detail-field"><span>End time</span><strong>{view.endTime}</strong></div></div></section><aside className="panel mini-panel"><div className="eyebrow">Next layer</div><h2>Classes</h2><p>Classes connected to this program will appear here.</p><Link href="/classes" className="text-button">View classes <ArrowRight size={14} /></Link></aside></div></>;
}

const classSchema = z.object({ name: z.string().min(2, "Name is required"), programId: z.string().min(1, "Choose a program") });

export function ClassList({ session }: { session: User }) {
  const query = useClasses(); const programs = usePrograms(); const sections = useSections(); const [search, setSearch] = useState("");
  if (query.isLoading) return <><PageHeader eyebrow="Academic hierarchy" title="Classes" description="Cohorts belong to a programme or shift and expose their sections." /><Loading label="Loading classes" /></>;
  if (query.isError) return <><PageHeader eyebrow="Academic hierarchy" title="Classes" description="Cohorts belong to a programme or shift and expose their sections." /><Empty title="Could not load classes" detail={classErrorMessage(query.error, "Could not load classes.")} /></>;
  if (sections.isError) return <><PageHeader eyebrow="Academic hierarchy" title="Classes" description="Cohorts belong to a programme or shift and expose their sections." /><Empty title="Could not load sections" detail={sectionErrorMessage(sections.error, "Could not load sections.")} /></>;
  const rows = (query.data || []).filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader eyebrow="Academic hierarchy" title="Classes" description="Cohorts belong to a programme or shift and expose their sections." action={hasPermission(session.role, "CLASS_CREATE") && <Link href="/classes/new" className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus size={16} />Add class</Link>} /><div className="hierarchy-banner"><span className="hierarchy-node">Academic Year</span><ArrowRight size={14} /><span className="hierarchy-node">Program / Shift</span><ArrowRight size={14} /><span className="hierarchy-node">Class</span><ArrowRight size={14} /><span className="hierarchy-node">Section</span></div><div className="list-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search classes" /></div>{rows.length === 0 ? <Empty title="No classes found" detail="Add the first class to establish this layer of the academic hierarchy." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Class</th><th>Programme / shift</th><th>Sections</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/classes/${row.id}`} className="table-link"><strong>{row.name}</strong></Link></td><td>{programs.data?.find((program) => program.id === row.programId)?.name || "—"}</td><td>{sections.data?.filter((section) => section.classId === row.id).length || 0}</td><td className="row-actions">{hasPermission(session.role, "CLASS_UPDATE") && <Link href={`/classes/${row.id}/edit`} className="icon-button" title="Edit record"><Settings2 size={15} /></Link>}</td></tr>)}</tbody></table></div><div className="table-foot"><span>{rows.length} records</span><span className="table-foot-note">No delete action is available for academic setup records</span></div></div>}</>;
}

export function ClassForm({ id, session }: { id?: string; session: User }) {
  const editing = Boolean(id); const query = useClass(id); const programs = usePrograms(); const save = useSaveClass(id); const [, setLocation] = useLocation();
  const form = useForm<{ name: string; programId: string }>({ resolver: zodResolver(classSchema), defaultValues: { name: "", programId: "" } });
  useEffect(() => { if (query.data) form.reset({ name: query.data.name, programId: query.data.programId }); }, [query.data, form]);
  if (!hasPermission(session.role, editing ? "CLASS_UPDATE" : "CLASS_CREATE")) return <AccessState role={session.role} />;
  if (editing && query.isLoading) return <Loading label="Loading class" />;
  if (editing && query.isError) return <Empty title="Could not load class" detail={classErrorMessage(query.error, "Class not found.")} />;
  if (editing && !query.data) return <Empty title="Class not found" detail="The requested class could not be found." />;
  const submit = (values: { name: string; programId: string }) => { const payload: ClassCreateRequest | ClassUpdateRequest = editing ? { name: values.name } : { name: values.name, programId: values.programId }; save.mutate(payload, { onSuccess: (saved) => { toast({ title: editing ? "Class updated" : "Class created", description: "The class record is ready." }); setLocation(`/classes/${saved.id}`); }, onError: (error) => toast({ title: "Could not save class", description: classErrorMessage(error, "Could not save class.") }) }); };
  return <><button className="back-link page-back" onClick={() => setLocation(id ? `/classes/${id}` : "/classes")}><ArrowLeft size={15} />Back to Classes</button><PageHeader eyebrow={editing ? "Edit academic setup" : "New academic setup"} title={editing ? "Edit class" : "Add class"} description="Keep each class connected to its programme or shift." /><form className="form-card" onSubmit={form.handleSubmit(submit, () => toast({ title: "Check the form", description: "A few required fields still need your attention." }))}><div className="form-grid"><Field form={form} name="name" label="Class name" /><SelectField form={form} name="programId" label="Programme / shift" options={(programs.data || []).map((program) => [program.id, program.name])} disabled={editing} /></div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation(id ? `/classes/${id}` : "/classes")}>Cancel</AppButton><AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create class"}<ArrowRight size={16} /></AppButton></div></form></>;
}

export function ClassDetail({ id, session }: { id: string; session: User }) {
  const query = useClass(id); const programs = usePrograms(); const sections = useSections(); const [, setLocation] = useLocation();
  if (query.isLoading) return <Loading label="Loading class" />;
  if (query.isError || !query.data) return <><button className="back-link page-back" onClick={() => setLocation("/classes")}><ArrowLeft size={15} />Back to Classes</button><Empty title="Class not found" detail={classErrorMessage(query.error, "Class not found.")} /></>;
  if (sections.isError) return <><button className="back-link page-back" onClick={() => setLocation("/classes")}><ArrowLeft size={15} />Back to Classes</button><Empty title="Could not load sections" detail={sectionErrorMessage(sections.error, "Could not load sections.")} /></>;
  const item = query.data; const program = programs.data?.find((value) => value.id === item.programId); const childRows = (sections.data || []).filter((section) => section.classId === id);
  return <><button className="back-link page-back" onClick={() => setLocation("/classes")}><ArrowLeft size={15} />Back to Classes</button><div className="detail-header"><div className="detail-title"><div className="hierarchy-emblem"><GraduationCap size={25} /></div><div><div className="eyebrow">Academic hierarchy</div><h1>{item.name}</h1><p>{program?.name || "Programme unavailable"}</p></div></div>{hasPermission(session.role, "CLASS_UPDATE") && <Link href={`/classes/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-semibold"><Settings2 size={15} />Edit</Link>}</div><div className="detail-grid"><section className="panel detail-panel"><div className="panel-head"><div><div className="eyebrow">Connected record</div><h2>Class</h2></div></div><div className="detail-fields"><div className="detail-field"><span>Class name</span><strong>{item.name}</strong></div><div className="detail-field"><span>Programme / shift</span><strong>{program?.name || "—"}</strong></div></div></section><aside className="panel mini-panel"><div className="eyebrow">Child records</div><h2>Sections</h2><p>This class currently exposes {childRows.length} section{childRows.length === 1 ? "" : "s"}.</p>{childRows.map((section) => <Link key={section.id} href={`/sections/${section.id}`} className="pending-item"><strong>Section {section.name}</strong><ArrowRight size={15} /></Link>)}{hasPermission(session.role, "CLASS_CREATE") && <Link href="/sections/new" className="text-button mt-4"><Plus size={14} />Add section</Link>}</aside></div></>;
}

const sectionSchema = z.object({ name: z.string().min(1, "Name is required"), classId: z.string().min(1, "Choose a class") });

export function SectionList({ session }: { session: User }) {
  const query = useSections(); const classes = useClasses(); const [search, setSearch] = useState("");
  if (query.isLoading || classes.isLoading) return <><PageHeader eyebrow="Academic hierarchy" title="Sections" description="Sections stay connected to their parent class." /><Loading label="Loading sections" /></>;
  if (query.isError) return <><PageHeader eyebrow="Academic hierarchy" title="Sections" description="Sections stay connected to their parent class." /><Empty title="Could not load sections" detail={sectionErrorMessage(query.error, "Could not load sections.")} /></>;
  if (classes.isError) return <><PageHeader eyebrow="Academic hierarchy" title="Sections" description="Sections stay connected to their parent class." /><Empty title="Could not load classes" detail={classErrorMessage(classes.error, "Could not load classes.")} /></>;
  const rows = (query.data || []).filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader eyebrow="Academic hierarchy" title="Sections" description="Sections stay connected to their parent class." action={hasPermission(session.role, "CLASS_CREATE") && <Link href="/sections/new" className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus size={16} />Add section</Link>} /><div className="hierarchy-banner"><span className="hierarchy-node">Academic Year</span><ArrowRight size={14} /><span className="hierarchy-node">Program / Shift</span><ArrowRight size={14} /><span className="hierarchy-node">Class</span><ArrowRight size={14} /><span className="hierarchy-node">Section</span></div><div className="list-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search sections" /></div>{rows.length === 0 ? <Empty title="No sections found" detail="Add the first section to establish this layer of the academic hierarchy." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Section</th><th>Class</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/sections/${row.id}`} className="table-link"><strong>{row.name}</strong></Link></td><td>{classes.data?.find((schoolClass) => schoolClass.id === row.classId)?.name || "—"}</td><td className="row-actions">{hasPermission(session.role, "CLASS_UPDATE") && <Link href={`/sections/${row.id}/edit`} className="icon-button" title="Edit section"><Settings2 size={15} /></Link>}</td></tr>)}</tbody></table></div><div className="table-foot"><span>{rows.length} records</span><span className="table-foot-note">No delete action is available for academic setup records</span></div></div>}</>;
}

export function SectionForm({ id, session }: { id?: string; session: User }) {
  const editing = Boolean(id); const sections = useSections(); const classes = useClasses(); const save = useSaveSection(id); const [, setLocation] = useLocation();
  const form = useForm<{ name: string; classId: string }>({ resolver: zodResolver(sectionSchema), defaultValues: { name: "", classId: "" } });
  useEffect(() => { if (editing && id && sections.data) { const item = sections.data.find((section) => section.id === id); if (item) form.reset({ name: item.name, classId: item.classId }); } }, [editing, id, sections.data, form]);
  if (!hasPermission(session.role, editing ? "CLASS_UPDATE" : "CLASS_CREATE")) return <AccessState role={session.role} />;
  if (sections.isLoading || classes.isLoading) return <Loading label="Loading section" />;
  if (sections.isError) return <Empty title="Could not load sections" detail={sectionErrorMessage(sections.error, "Could not load sections.")} />;
  if (classes.isError) return <Empty title="Could not load classes" detail={classErrorMessage(classes.error, "Could not load classes.")} />;
  const item = editing ? sections.data?.find((section) => section.id === id) : undefined;
  if (editing && !item) return <Empty title="Section not found" detail="The requested section could not be found." />;
  const submit = (values: { name: string; classId: string }) => { const payload: SectionCreateRequest | SectionUpdateRequest = editing ? { name: values.name } : { name: values.name, classId: values.classId }; save.mutate(payload, { onSuccess: (saved) => { toast({ title: editing ? "Section updated" : "Section created", description: "The section record is ready." }); setLocation(saved?.id ? `/sections/${saved.id}` : "/sections"); }, onError: (error) => toast({ title: "Could not save section", description: sectionErrorMessage(error, "Could not save section.") }) }); };
  return <><button className="back-link page-back" onClick={() => setLocation(id ? `/sections/${id}` : "/sections")}><ArrowLeft size={15} />Back to Sections</button><PageHeader eyebrow={editing ? "Edit academic setup" : "New academic setup"} title={editing ? "Edit section" : "Add section"} description="Keep each section connected to its parent class." /><form className="form-card" onSubmit={form.handleSubmit(submit, () => toast({ title: "Check the form", description: "A few required fields still need your attention." }))}><div className="form-grid"><Field form={form} name="name" label="Section name" /><SelectField form={form} name="classId" label="Parent class" options={(classes.data || []).map((schoolClass) => [schoolClass.id, schoolClass.name])} disabled={editing} /></div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation(id ? `/sections/${id}` : "/sections")}>Cancel</AppButton><AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create section"}<ArrowRight size={16} /></AppButton></div></form></>;
}

export function SectionDetail({ id, session }: { id: string; session: User }) {
  const sections = useSections(); const classes = useClasses(); const [, setLocation] = useLocation();
  if (sections.isLoading || classes.isLoading) return <Loading label="Loading section" />;
  if (sections.isError) return <Empty title="Could not load sections" detail={sectionErrorMessage(sections.error, "Could not load sections.")} />;
  if (classes.isError) return <Empty title="Could not load classes" detail={classErrorMessage(classes.error, "Could not load classes.")} />;
  const item = sections.data?.find((section) => section.id === id); const parent = item && classes.data?.find((schoolClass) => schoolClass.id === item.classId);
  if (!item) return <Empty title="Section not found" detail="The requested section could not be found." />;
  return <><button className="back-link page-back" onClick={() => setLocation("/sections")}><ArrowLeft size={15} />Back to Sections</button><div className="detail-header"><div className="detail-title"><div className="hierarchy-emblem"><GraduationCap size={25} /></div><div><div className="eyebrow">Academic hierarchy</div><h1>{item.name}</h1><p>{parent?.name || "Class unavailable"}</p></div></div>{hasPermission(session.role, "CLASS_UPDATE") && <Link href={`/sections/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-semibold"><Settings2 size={15} />Edit</Link>}</div><div className="detail-grid"><section className="panel detail-panel"><div className="panel-head"><div><div className="eyebrow">Connected record</div><h2>Section</h2></div></div><div className="detail-fields"><div className="detail-field"><span>Section name</span><strong>{item.name}</strong></div><div className="detail-field"><span>Class</span><strong>{parent?.name || "—"}</strong></div></div></section></div></>;
}

const subjectSchema = z.object({ name: z.string().trim().min(1, "Name is required").min(2, "Name is too short"), classId: z.string().min(1, "Choose a class") });

export function SubjectList({ session }: { session: User }) {
  const classes = useClasses(); const [classId, setClassId] = useState(""); const query = useSubjectsByClass(classId); const remove = useDeleteSubject(); const [, setLocation] = useLocation();
  useEffect(() => { if (!classId && classes.data?.[0]) setClassId(classes.data[0].id); }, [classId, classes.data]);
  if (classes.isLoading) return <><PageHeader title="Subjects" description="Subjects available within a class." /><Loading label="Loading classes" /></>;
  if (classes.isError) return <><PageHeader title="Subjects" description="Subjects available within a class." /><Empty title="Could not load classes" detail={classErrorMessage(classes.error, "Could not load classes.")} /></>;
  if (query.isLoading) return <><PageHeader title="Subjects" description="Subjects available within a class." /><Loading label="Loading subjects" /></>;
  if (query.isError) return <><PageHeader title="Subjects" description="Subjects available within a class." /><Empty title="Could not load subjects" detail={subjectErrorMessage(query.error, "Could not load subjects.")} /></>;
  const selectedClass = classes.data?.find((schoolClass) => schoolClass.id === classId);
  const rows = query.data || [];
  const deleteSubject = (id: string) => { if (!window.confirm("Delete this subject? This soft-deletes the subject and permanently removes related teaching assignments. This action cannot be undone from the current system.")) return; remove.mutate({ id, classId }, { onSuccess: () => toast({ title: "Subject deleted", description: "The subject and related teaching assignments were removed." }), onError: (error) => toast({ title: "Could not delete subject", description: subjectErrorMessage(error, "Could not delete subject.") }) }); };
  return <><PageHeader title="Subjects" description="Subjects available within a class." action={hasPermission(session.role, "CLASS_CREATE") && <Link href="/subjects/new" className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus size={16} />Add subject</Link>} /><div className="list-toolbar"><label className="field"><span>Class</span><select value={classId} onChange={(event) => setClassId(event.target.value)}>{(classes.data || []).map((schoolClass) => <option key={schoolClass.id} value={schoolClass.id}>{schoolClass.name}</option>)}</select></label></div>{rows.length === 0 ? <Empty title="No subjects found" detail={`No subjects are available for ${selectedClass?.name || "this class"}.`} /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Subject</th><th>Class</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/subjects/${row.id}`} className="table-link"><strong>{row.name}</strong></Link></td><td>{selectedClass?.name || "—"}</td><td className="row-actions">{hasPermission(session.role, "CLASS_UPDATE") && <><Link href={`/subjects/${row.id}/edit`} className="icon-button" title="Edit subject"><Settings2 size={15} /></Link><button type="button" className="text-button ml-3" onClick={() => deleteSubject(row.id)} disabled={remove.isPending}>Delete</button></>}</td></tr>)}</tbody></table></div><div className="table-foot"><span>{rows.length} records</span></div></div>}</>;
}

export function SubjectForm({ id, session }: { id?: string; session: User }) {
  const editing = Boolean(id); const classes = useClasses(); const query = useSubject(id); const save = useSaveSubject(id); const [, setLocation] = useLocation();
  const form = useForm<{ name: string; classId: string }>({ resolver: zodResolver(subjectSchema), defaultValues: { name: "", classId: "" } });
  useEffect(() => { if (query.data) form.reset({ name: query.data.name, classId: query.data.classId }); else if (!editing && classes.data?.[0]) form.setValue("classId", classes.data[0].id); }, [query.data, classes.data, editing, form]);
  if (!hasPermission(session.role, editing ? "CLASS_UPDATE" : "CLASS_CREATE")) return <AccessState role={session.role} />;
  if (classes.isLoading || (editing && query.isLoading)) return <Loading label="Loading subject" />;
  if (classes.isError) return <Empty title="Could not load classes" detail={classErrorMessage(classes.error, "Could not load classes.")} />;
  if (editing && query.isError) return <Empty title="Could not load subject" detail={subjectErrorMessage(query.error, "Subject not found.")} />;
  if (editing && !query.data) return <Empty title="Subject not found" detail="The requested subject could not be found." />;
  const submit = (values: { name: string; classId: string }) => { const payload: SubjectCreateRequest | SubjectUpdateRequest = editing ? { name: values.name.trim() } : { classId: values.classId, name: values.name.trim() }; save.mutate(payload, { onSuccess: (saved) => { toast({ title: editing ? "Subject updated" : "Subject created", description: "The subject record is ready." }); setLocation(`/subjects/${saved.id}`); }, onError: (error) => toast({ title: "Could not save subject", description: subjectErrorMessage(error, "Could not save subject.") }) }); };
  return <><button className="back-link page-back" onClick={() => setLocation(id ? `/subjects/${id}` : "/subjects")}><ArrowLeft size={15} />Back to Subjects</button><PageHeader eyebrow={editing ? "Edit academic setup" : "New academic setup"} title={editing ? "Edit subject" : "Add subject"} description="Connect each subject to its class." /><form className="form-card" onSubmit={form.handleSubmit(submit, () => toast({ title: "Check the form", description: "A few required fields still need your attention." }))}><div className="form-grid"><Field form={form} name="name" label="Subject name" /><SelectField form={form} name="classId" label="Class" options={(classes.data || []).map((schoolClass) => [schoolClass.id, schoolClass.name])} disabled={editing} /></div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation(id ? `/subjects/${id}` : "/subjects")}>Cancel</AppButton><AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create subject"}<ArrowRight size={16} /></AppButton></div></form></>;
}

export function SubjectDetail({ id, session }: { id: string; session: User }) {
  const query = useSubject(id); const classes = useClasses(); const remove = useDeleteSubject(); const [, setLocation] = useLocation();
  if (query.isLoading || classes.isLoading) return <Loading label="Loading subject" />;
  if (query.isError) return <Empty title="Could not load subject" detail={subjectErrorMessage(query.error, "Subject not found.")} />;
  if (classes.isError) return <Empty title="Could not load classes" detail={classErrorMessage(classes.error, "Could not load classes.")} />;
  if (!query.data) return <Empty title="Subject not found" detail="The requested subject could not be found." />;
  const item = query.data; const parent = classes.data?.find((schoolClass) => schoolClass.id === item.classId);
  const handleDelete = () => { if (!window.confirm("Delete this subject? This soft-deletes the subject and permanently removes related teaching assignments. This action cannot be undone from the current system.")) return; remove.mutate({ id: item.id, classId: item.classId }, { onSuccess: () => { toast({ title: "Subject deleted", description: "The subject and related teaching assignments were removed." }); setLocation("/subjects"); }, onError: (error) => toast({ title: "Could not delete subject", description: subjectErrorMessage(error, "Could not delete subject.") }) }); };
  return <><button className="back-link page-back" onClick={() => setLocation("/subjects")}><ArrowLeft size={15} />Back to Subjects</button><div className="detail-header"><div className="detail-title"><div className="hierarchy-emblem"><GraduationCap size={25} /></div><div><div className="eyebrow">Academic subject</div><h1>{item.name}</h1><p>{parent?.name || "Class unavailable"}</p></div></div><div className="detail-actions">{hasPermission(session.role, "CLASS_UPDATE") && <><Link href={`/subjects/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-semibold"><Settings2 size={15} />Edit</Link><AppButton variant="danger" onClick={handleDelete} disabled={remove.isPending}>{remove.isPending ? "Deleting…" : "Delete"}</AppButton></>}</div></div><div className="detail-grid"><section className="panel detail-panel"><div className="panel-head"><div><div className="eyebrow">Connected record</div><h2>Subject</h2></div></div><div className="detail-fields"><div className="detail-field"><span>Subject name</span><strong>{item.name}</strong></div><div className="detail-field"><span>Class</span><strong>{parent?.name || "—"}</strong></div></div></section></div></>;
}

export function SetupList({ resource, session }: { resource: SetupResource; session: User }) {
  const meta = setupMeta[resource]; const query = useResource(resource); const sections = useResource("sections"); const [search, setSearch] = useState(""); const canCreate = hasPermission(session.role, meta.create); const actualRoute = resource === "programs" ? "academic-programs" : resource === "academicYears" ? "academic-years" : resource;
  if (query.isLoading) return <><PageHeader title={meta.title} /><Loading /></>;
  const rows = ((query.data || []) as Array<Record<string, unknown>>).filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
  const columns = resource === "academicYears" ? [["name", "Year"], ["schoolId", "School ID"], ["startDate", "Starts"], ["endDate", "Ends"]] : resource === "programs" ? [["name", "Programme / shift"], ["academicYear", "Academic year"], ["primary", "Primary"], ["daysOfWeek", "Days"], ["startTime", "Start"], ["endTime", "End"]] : resource === "classes" ? [["name", "Class"], ["program", "Programme / shift"], ["sectionCount", "Sections"]] : [["name", "Section"], ["class", "Class"]];
  return <><PageHeader eyebrow="Academic hierarchy" title={meta.title} description={resource === "academicYears" ? "Start at the academic cycle, then connect programmes, classes, and sections." : resource === "programs" ? "The programme and shift layer underneath each academic year." : resource === "classes" ? "Cohorts belong to a programme or shift and expose their sections." : "Sections stay connected to their parent class."} action={canCreate && <Link href={`/${actualRoute}/new`} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground" data-testid={`link-new-${resource}`}><Plus size={16} />Add {meta.singular}</Link>} /><div className="hierarchy-banner"><span className="hierarchy-node">Academic Year</span><ArrowRight size={14} /><span className="hierarchy-node">Program / Shift</span><ArrowRight size={14} /><span className="hierarchy-node">Class</span><ArrowRight size={14} /><span className="hierarchy-node">Section</span></div><div className="list-toolbar"><SearchBox value={search} onChange={setSearch} placeholder={`Search ${meta.title.toLowerCase()}`} /></div>{rows.length === 0 ? <Empty title={`No ${meta.title.toLowerCase()} found`} detail="Add the first record to establish this layer of the academic hierarchy." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr>{columns.map(([, label]) => <th key={label}>{label}</th>)}<th /></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}>{columns.map(([key]) => <td key={key}>{key === "name" ? <Link href={`/${actualRoute}/${row.id}`} className="table-link"><strong>{String(row[key])}</strong></Link> : key === "primary" ? <Status>{row[key] ? "Active" : "Pending"}</Status> : key === "daysOfWeek" ? String((row[key] as string[]).join(" · ")) : key === "sectionCount" ? String(sections.data?.filter((section) => section.classId === row.id).length || 0) : key.toLowerCase().includes("date") ? date(String(row[key])) : String(row[key] ?? "—")}</td>)}<td className="row-actions">{hasPermission(session.role, meta.update) && <Link href={`/${actualRoute}/${row.id}/edit`} className="icon-button" title="Edit record"><Settings2 size={15} /></Link>}</td></tr>)}</tbody></table></div><div className="table-foot"><span>{rows.length} records</span><span className="table-foot-note">No delete action is available for academic setup records</span></div></div>}</>;
}

export function SetupForm({ resource, id, session }: { resource: SetupResource; id?: string; session: User }) {
  const meta = setupMeta[resource]; const actualRoute = resource === "programs" ? "academic-programs" : resource; const query = useItem(resource, id); const save = useSaveResource(resource); const [, setLocation] = useLocation(); const editing = !!id; const canEdit = hasPermission(session.role, editing ? meta.update : meta.create); const years = useResource("academicYears"); const programs = useResource("programs"); const classes = useResource("classes");
  const defaults: Record<string, unknown> = resource === "academicYears" ? { schoolId: "NAC-BLR", name: "2026–27", startDate: "2026-06-01", endDate: "2027-05-31" } : resource === "programs" ? { name: "Regular Day Programme", academicYearId: "ay25", primary: "true", daysOfWeek: "Monday, Tuesday, Wednesday, Thursday, Friday", startTime: "09:00", endTime: "16:00" } : resource === "classes" ? { name: "B.A. Psychology", programId: "prg-day" } : { name: "A", classId: "cls-csc" };
  const form = useForm<Record<string, unknown>>({ resolver: zodResolver(setupSchema[resource]), defaultValues: defaults });
  useEffect(() => { if (query.item) { const item = query.item as Record<string, unknown>; form.reset({ ...defaults, ...item, primary: typeof item.primary === "boolean" ? String(item.primary) : item.primary, daysOfWeek: Array.isArray(item.daysOfWeek) ? item.daysOfWeek.join(", ") : item.daysOfWeek }); } }, [query.item]); // eslint-disable-line react-hooks/exhaustive-deps
  if (!canEdit) return <AccessState role={session.role} />; if (editing && query.isLoading) return <Loading />; if (editing && !query.item) return <Empty title="Record not found" detail="This setup record is no longer in the workspace." />;
  const submit = (values: Record<string, unknown>) => {
    const record: Record<string, unknown> = { ...values };
    if (resource === "programs") { const year = (years.data || []).find((item) => item.id === values.academicYearId); record.academicYear = year?.name || ""; record.primary = values.primary === "true"; record.daysOfWeek = String(values.daysOfWeek).split(",").map((day) => day.trim()).filter(Boolean); }
    if (resource === "classes") { const program = (programs.data || []).find((item) => item.id === values.programId); record.program = program?.name || ""; }
    if (resource === "sections") { const parent = (classes.data || []).find((item) => item.id === values.classId); record.class = parent?.name || ""; }
    save.mutate({ id, value: record } as never, { onSuccess: (saved) => { toast({ title: editing ? "Record updated" : "Record created", description: `${meta.singular} saved in the academic hierarchy.` }); setLocation(`/${actualRoute}/${id || (saved as { id: string }).id}`); }, onError: () => toast({ title: "Could not save record" }) });
  };
  return <><button className="back-link page-back" onClick={() => setLocation(`/${actualRoute}`)}><ArrowLeft size={15} />Back to {meta.title}</button><PageHeader eyebrow={editing ? "Edit academic setup" : "New academic setup"} title={editing ? `Edit ${meta.singular}` : `Add ${meta.singular}`} description="Keep each layer connected to its parent record." /><form className="form-card" onSubmit={form.handleSubmit(submit, () => toast({ title: "Check the form", description: "A few required fields still need your attention." }))}><div className="form-grid">{resource === "academicYears" && <><Field form={form} name="schoolId" label="School ID" /><Field form={form} name="name" label="Academic year name" /><Field form={form} name="startDate" label="Start date" type="date" /><Field form={form} name="endDate" label="End date" type="date" /></>}{resource === "programs" && <><Field form={form} name="name" label="Programme / shift name" /><SelectField form={form} name="academicYearId" label="Academic year" options={(years.data || []).map((year) => [year.id, year.name])} /><SelectField form={form} name="primary" label="Primary programme" options={[["true", "Primary"], ["false", "Non-primary"]]} /><Field form={form} name="daysOfWeek" label="Days of week" /><Field form={form} name="startTime" label="Start time" type="time" /><Field form={form} name="endTime" label="End time" type="time" /></>}{resource === "classes" && <><Field form={form} name="name" label="Class name" /><SelectField form={form} name="programId" label="Programme / shift" options={(programs.data || []).map((program) => [program.id, program.name])} /></>}{resource === "sections" && <><Field form={form} name="name" label="Section name" /><SelectField form={form} name="classId" label="Parent class" options={(classes.data || []).map((schoolClass) => [schoolClass.id, schoolClass.name])} /></>}</div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation(`/${actualRoute}`)}>Cancel</AppButton><AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : `Create ${meta.singular}`}<ArrowRight size={16} /></AppButton></div></form></>;
}
export function Field({ form, name, label, type = "text", disabled = false }: { form: ReturnType<typeof useForm<Record<string, unknown>>>; name: string; label: string; type?: string; disabled?: boolean }) { return <div className="field"><label htmlFor={name}>{label}</label><input id={name} type={type} disabled={disabled} {...form.register(name)} />{form.formState.errors[name] && <span className="field-error">{String(form.formState.errors[name]?.message)}</span>}</div>; }
export function SelectField({ form, name, label, options, disabled = false, onChange }: { form?: ReturnType<typeof useForm<Record<string, unknown>>>; name: string; label: string; options: string[][]; disabled?: boolean; onChange?: (event: React.ChangeEvent<HTMLSelectElement>) => void }) { return <div className="field"><label htmlFor={name}>{label}</label><select id={name} disabled={disabled} {...(form ? form.register(name, { onChange }) : {})}>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select>{form?.formState.errors[name] && <span className="field-error">{String(form.formState.errors[name]?.message)}</span>}</div>; }

export function SetupDetail({ resource, id, session }: { resource: SetupResource; id: string; session: User }) {
  const meta = setupMeta[resource]; const route = resource === "programs" ? "academic-programs" : resource === "academicYears" ? "academic-years" : resource; const query = useItem(resource, id); const [, setLocation] = useLocation(); const item = query.item as Record<string, unknown> | undefined; const canUpdate = hasPermission(session.role, meta.update); const sections = useResource("sections"); const classes = useResource("classes"); const programs = useResource("programs");
  if (query.isLoading) return <Loading />; if (!item) return <Empty title="Record not found" detail="This record may have been removed." action={<Link href={`/${route}`} className="text-button">Back to {meta.title}</Link>} />;
  const childRows = resource === "classes" ? (sections.data || []).filter((section) => section.classId === id) : [];
  return <><button className="back-link page-back" onClick={() => setLocation(`/${route}`)}><ArrowLeft size={15} />Back to {meta.title}</button><div className="detail-header"><div className="detail-title"><div className="hierarchy-emblem"><GraduationCap size={25} /></div><div><div className="eyebrow">Academic hierarchy</div><h1>{String(item.name)}</h1><p>{resource === "academicYears" ? `${item.schoolId} · ${date(String(item.startDate))} to ${date(String(item.endDate))}` : resource === "programs" ? `${item.academicYear} · ${item.primary ? "Primary" : "Non-primary"}` : resource === "classes" ? String(item.program) : String(item.class)}</p></div></div>{canUpdate && <Link href={`/${route}/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-semibold"><Settings2 size={15} />Edit</Link>}</div><div className="detail-grid"><section className="panel detail-panel"><div className="panel-head"><div><div className="eyebrow">Connected record</div><h2>{meta.title.slice(0, -1)}</h2></div></div><div className="detail-fields">{Object.entries(item).filter(([key]) => key !== "id").map(([key, value]) => <div className="detail-field" key={key}><span>{titleCase(key)}</span><strong>{Array.isArray(value) ? value.join(" · ") : key.toLowerCase().includes("date") ? date(String(value)) : String(value)}</strong></div>)}</div></section>{resource === "classes" && <aside className="panel mini-panel"><div className="eyebrow">Child records</div><h2>Sections</h2><p>This class currently exposes {childRows.length} section{childRows.length === 1 ? "" : "s"}.</p>{childRows.map((section) => <Link key={section.id} href={`/sections/${section.id}`} className="pending-item"><strong>Section {section.name}</strong><ArrowRight size={15} /></Link>)}{hasPermission(session.role, "CLASS_CREATE") && <Link href="/sections/new" className="text-button mt-4"><Plus size={14} />Add section</Link>}</aside>}{resource === "academicYears" && <aside className="panel mini-panel"><div className="eyebrow">Next layer</div><h2>Programs & shifts</h2><p>{programs.data?.filter((program) => program.academicYearId === id).length || 0} connected programmes use this academic year.</p><Link href="/academic-programs" className="text-button">View programmes <ArrowRight size={14} /></Link></aside>}{resource === "programs" && <aside className="panel mini-panel"><div className="eyebrow">Next layer</div><h2>Classes</h2><p>{(classes.data || []).filter((schoolClass) => schoolClass.programId === id).length} classes belong to this programme or shift.</p><Link href="/classes" className="text-button">View classes <ArrowRight size={14} /></Link></aside>}</div></>;
}

