import { useEffect, useState } from "react";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Link, useLocation } from "wouter";
import { ArrowLeft, ArrowRight, Plus, Settings2 } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { classErrorMessage, useClass, useClasses, useSaveClass, type ClassCreateRequest, type ClassUpdateRequest } from "@/lib/classes-api";
import { sectionErrorMessage, useSaveSection, useSections, useSectionsByClass, type SectionCreateRequest, type SectionUpdateRequest } from "@/lib/sections-api";
import { subjectErrorMessage, useDeleteSubject, useSaveSubject, useSubject, useSubjectsByClass, type SubjectCreateRequest, type SubjectUpdateRequest } from "@/lib/subjects-api";
import { staffErrorMessage, useSaveStaff, useStaff, useStaffMember, useUpdateStaffStatus, type StaffCreateRequest, type StaffUpdateRequest } from "@/lib/staff-api";
import { teachingAssignmentErrorMessage, useDeleteTeachingAssignment, useSaveTeachingAssignment, useTeachingAssignments, type TeachingAssignmentCreateRequest, type TeachingAssignmentUpdateRequest } from "@/lib/teaching-assignments-api";
import { type User, hasPermission } from "@/lib/mock-erp";
import { AccessState, AppButton, Empty, Loading, PageHeader, SearchBox, SelectBox, Status, date } from "@/pages/page-primitives";
import { Field, SelectField } from "@/pages/academic-pages";
const staffSchema = z.object({ staffCode: z.string().trim().min(1, "Staff code is required"), firstName: z.string().trim().min(1, "First name is required"), lastName: z.string().trim().min(1, "Last name is required"), email: z.string().trim().email("Enter a valid email"), phoneNumber: z.string().trim().min(10, "Enter a valid phone number"), dateOfBirth: z.string().min(1, "Date of birth is required") });
const staffName = (staff: { firstName: string; lastName: string }) => `${staff.firstName} ${staff.lastName}`.trim();

export function StaffList({ session }: { session: User }) {
  const query = useStaff(); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("All");
  if (query.isLoading) return <><PageHeader title="Staff" description="Faculty and operations colleagues at Nalanda." /><Loading label="Loading Staff" /></>;
  if (query.isError) return <><PageHeader title="Staff" description="Faculty and operations colleagues at Nalanda." /><Empty title="Could not load Staff" detail={staffErrorMessage(query.error, "Could not load Staff.")} /></>;
  const rows = (query.data || []).filter((row) => { const matchesSearch = JSON.stringify(row).toLowerCase().includes(search.toLowerCase()); const status = row.status ? "Active" : "Inactive"; return matchesSearch && (filter === "All" || filter === status); });
  return <><PageHeader title="Staff" description="Faculty and operations colleagues at Nalanda." action={hasPermission(session.role, "STAFF_CREATE") && <Link href="/staff/new" className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus size={16} />Add staff member</Link>} /><div className="list-toolbar"><SearchBox value={search} onChange={setSearch} /><div className="toolbar-right"><SelectBox value={filter} onChange={setFilter} label="Status" options={["Active", "Inactive"]} /></div></div>{rows.length === 0 ? <Empty title="No Staff found" detail="Try a different search or clear the current filter." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Staff code</th><th>Name</th><th>Email</th><th>Phone</th><th>Date of birth</th><th>Status</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.staffCode}</td><td><Link href={`/staff/${row.id}`} className="person-cell table-link"><Avatar user={{ name: staffName(row) }} size="sm" /><strong>{staffName(row)}</strong></Link></td><td>{row.email}</td><td>{row.phoneNumber}</td><td>{date(row.dateOfBirth)}</td><td><Status>{row.status ? "Active" : "Inactive"}</Status></td><td className="row-actions">{hasPermission(session.role, "STAFF_UPDATE") && <Link href={`/staff/${row.id}/edit`} className="icon-button" title="Edit Staff"><Settings2 size={15} /></Link>}</td></tr>)}</tbody></table></div><div className="table-foot"><span>Showing {rows.length} of {rows.length} records</span></div></div>}</>;
}

export function StaffForm({ id, session }: { id?: string; session: User }) {
  const editing = Boolean(id); const query = useStaffMember(id); const save = useSaveStaff(id); const [, setLocation] = useLocation();
  const form = useForm<StaffCreateRequest>({ resolver: zodResolver(staffSchema), defaultValues: { staffCode: "", firstName: "", lastName: "", email: "", phoneNumber: "", dateOfBirth: "" } });
  useEffect(() => { if (query.data) form.reset({ staffCode: query.data.staffCode, firstName: query.data.firstName, lastName: query.data.lastName, email: query.data.email, phoneNumber: query.data.phoneNumber, dateOfBirth: query.data.dateOfBirth }); }, [query.data, form]);
  if (!hasPermission(session.role, editing ? "STAFF_UPDATE" : "STAFF_CREATE")) return <AccessState role={session.role} />;
  if (editing && query.isLoading) return <Loading label="Loading Staff" />;
  if (editing && query.isError) return <Empty title="Could not load Staff" detail={staffErrorMessage(query.error, "Staff member not found.")} />;
  if (editing && !query.data) return <Empty title="Staff member not found" detail="The requested Staff record could not be found." />;
  const submit = (values: StaffCreateRequest) => { const payload: StaffCreateRequest | StaffUpdateRequest = { staffCode: values.staffCode.trim(), firstName: values.firstName.trim(), lastName: values.lastName.trim(), email: values.email.trim(), phoneNumber: values.phoneNumber.trim(), dateOfBirth: values.dateOfBirth }; save.mutate(payload, { onSuccess: (saved) => { toast({ title: editing ? "Staff updated" : "Staff created", description: "The Staff record is ready." }); setLocation(`/staff/${saved.id}`); }, onError: (error) => toast({ title: "Could not save Staff", description: staffErrorMessage(error, "Could not save Staff.") }) }); };
  return <><button className="back-link page-back" onClick={() => setLocation(id ? `/staff/${id}` : "/staff")}><ArrowLeft size={15} />Back to Staff</button><PageHeader eyebrow={editing ? "Edit Staff" : "New Staff"} title={editing ? "Edit Staff member" : "Add Staff member"} description="Manage only the Staff fields supported by the backend." /><form className="form-card" onSubmit={form.handleSubmit(submit, () => toast({ title: "Check the form", description: "A few required fields still need your attention." }))}><div className="form-grid"><Field form={form} name="staffCode" label="Staff code" /><Field form={form} name="firstName" label="First name" /><Field form={form} name="lastName" label="Last name" /><Field form={form} name="email" label="Email" type="email" /><Field form={form} name="phoneNumber" label="Phone number" /><Field form={form} name="dateOfBirth" label="Date of birth" type="date" /></div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation(id ? `/staff/${id}` : "/staff")}>Cancel</AppButton><AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create Staff member"}<ArrowRight size={16} /></AppButton></div></form></>;
}

export function StaffDetail({ id, session }: { id: string; session: User }) {
  const query = useStaffMember(id); const updateStatus = useUpdateStaffStatus(); const [, setLocation] = useLocation();
  if (query.isLoading) return <Loading label="Loading Staff" />;
  if (query.isError) return <Empty title="Could not load Staff" detail={staffErrorMessage(query.error, "Staff member not found.")} />;
  if (!query.data) return <Empty title="Staff member not found" detail="The requested Staff record could not be found." />;
  const item = query.data; const fullName = staffName(item); const toggleStatus = () => updateStatus.mutate({ id: item.id, status: !item.status }, { onSuccess: () => toast({ title: "Staff status updated" }), onError: (error) => toast({ title: "Could not update Staff status", description: staffErrorMessage(error, "Could not update Staff status.") }) });
  return <><button className="back-link page-back" onClick={() => setLocation("/staff")}><ArrowLeft size={15} />Back to Staff</button><div className="detail-header"><div className="detail-title"><Avatar user={{ name: fullName }} size="lg" /><div><div className="eyebrow">{item.staffCode}</div><h1>{fullName}</h1><p>{item.email}</p></div></div><div className="detail-actions">{hasPermission(session.role, "STAFF_UPDATE") && <><Link href={`/staff/${id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-semibold"><Settings2 size={15} />Edit</Link><AppButton variant={item.status ? "soft" : "primary"} onClick={toggleStatus} disabled={updateStatus.isPending}>{updateStatus.isPending ? "Updating…" : item.status ? "Set inactive" : "Set active"}</AppButton></>}</div></div><div className="detail-grid"><section className="panel detail-panel"><div className="panel-head"><div><div className="eyebrow">Staff record</div><h2>Information</h2></div><Status>{item.status ? "Active" : "Inactive"}</Status></div><div className="detail-fields"><div className="detail-field"><span>Staff code</span><strong>{item.staffCode}</strong></div><div className="detail-field"><span>First name</span><strong>{item.firstName}</strong></div><div className="detail-field"><span>Last name</span><strong>{item.lastName}</strong></div><div className="detail-field"><span>Email</span><strong>{item.email}</strong></div><div className="detail-field"><span>Phone number</span><strong>{item.phoneNumber}</strong></div><div className="detail-field"><span>Date of birth</span><strong>{date(item.dateOfBirth)}</strong></div></div></section></div></>;
}

const assignmentSchema = z.object({ staffId: z.string().min(1, "Choose a Staff member"), classId: z.string().min(1, "Choose a class"), subjectId: z.string().min(1, "Choose a subject"), sectionId: z.string().min(1, "Choose a section") });
const relationLabel = (value?: { name?: string; firstName?: string; lastName?: string }) => value?.name || `${value?.firstName || ""} ${value?.lastName || ""}`.trim() || "—";

export function TeachingAssignmentsList({ session }: { session: User }) {
  const query = useTeachingAssignments(); const remove = useDeleteTeachingAssignment(); const [search, setSearch] = useState("");
  if (query.isLoading) return <><PageHeader title="Teaching assignments" description="Connect Staff, Subjects, Classes, and Sections." /><Loading label="Loading teaching assignments" /></>;
  if (query.isError) return <><PageHeader title="Teaching assignments" description="Connect Staff, Subjects, Classes, and Sections." /><Empty title="Could not load teaching assignments" detail={teachingAssignmentErrorMessage(query.error, "Could not load teaching assignments.")} /></>;
  const rows = (query.data || []).filter((row) => JSON.stringify({ staff: relationLabel(row.staff), subject: relationLabel(row.subject), class: relationLabel(row.class), section: relationLabel(row.section) }).toLowerCase().includes(search.toLowerCase()));
  const deleteAssignment = (id: string) => { if (!window.confirm("Delete this teaching assignment permanently? This is a hard delete and cannot be restored.")) return; remove.mutate(id, { onSuccess: () => toast({ title: "Teaching assignment deleted" }), onError: (error) => toast({ title: "Could not delete teaching assignment", description: teachingAssignmentErrorMessage(error, "Teaching assignment not found.") }) }); };
  return <><PageHeader title="Teaching assignments" description="Connect Staff, Subjects, Classes, and Sections." action={hasPermission(session.role, "STAFF_UPDATE") && <Link href="/teaching-assignments/new" className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus size={16} />Add assignment</Link>} /><div className="list-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search assignments" /></div>{rows.length === 0 ? <Empty title="No teaching assignments found" detail="Add an assignment to connect a Staff member with a class subject and section." /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Staff</th><th>Subject</th><th>Class</th><th>Section</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{relationLabel(row.staff)}</td><td>{relationLabel(row.subject)}</td><td>{relationLabel(row.class)}</td><td>{relationLabel(row.section)}</td><td className="row-actions">{hasPermission(session.role, "STAFF_UPDATE") && <><Link href={`/teaching-assignments/${row.id}/edit`} className="icon-button" title="Edit assignment"><Settings2 size={15} /></Link><button type="button" className="text-button ml-3" onClick={() => deleteAssignment(row.id)} disabled={remove.isPending}>Delete</button></>}</td></tr>)}</tbody></table></div><div className="table-foot"><span>{rows.length} records</span></div></div>}</>;
}

export function TeachingAssignmentForm({ id, session }: { id?: string; session: User }) {
  const editing = Boolean(id); const assignments = useTeachingAssignments(); const staff = useStaff(); const classes = useClasses(); const save = useSaveTeachingAssignment(id); const remove = useDeleteTeachingAssignment(); const [, setLocation] = useLocation();
  const form = useForm<TeachingAssignmentCreateRequest>({ resolver: zodResolver(assignmentSchema), defaultValues: { staffId: "", classId: "", subjectId: "", sectionId: "" } });
  const classId = form.watch("classId"); const subjects = useSubjectsByClass(classId); const sections = useSectionsByClass(classId);
  const assignment = editing ? assignments.data?.find((item) => item.id === id) : undefined;
  useEffect(() => { if (assignment) form.reset({ staffId: assignment.staffId, classId: assignment.classId, subjectId: assignment.subjectId, sectionId: assignment.sectionId }); }, [assignment, form]);
  useEffect(() => { if (!editing && classId) { form.setValue("subjectId", ""); form.setValue("sectionId", ""); } }, [classId, editing, form]);
  if (!hasPermission(session.role, "STAFF_UPDATE")) return <AccessState role={session.role} />;
  if (staff.isLoading || classes.isLoading || (editing && assignments.isLoading)) return <Loading label="Loading teaching assignment" />;
  if (staff.isError) return <Empty title="Could not load Staff" detail={staffErrorMessage(staff.error, "Could not load Staff.")} />;
  if (classes.isError) return <Empty title="Could not load classes" detail={classErrorMessage(classes.error, "Could not load classes.")} />;
  if (editing && assignments.isError) return <Empty title="Could not load teaching assignments" detail={teachingAssignmentErrorMessage(assignments.error, "Could not load teaching assignment.")} />;
  if (editing && !assignment) return <Empty title="Teaching assignment not found" detail="The requested assignment could not be found." />;
  if (subjects.isError || sections.isError) return <Empty title="Could not load assignment options" detail={teachingAssignmentErrorMessage(subjects.error || sections.error, "Could not load Subjects or Sections.")} />;
  const submit = (values: TeachingAssignmentCreateRequest) => { const payload: TeachingAssignmentCreateRequest | TeachingAssignmentUpdateRequest = editing ? { subjectId: values.subjectId, classId: values.classId, sectionId: values.sectionId } : values; save.mutate(payload, { onSuccess: () => { toast({ title: editing ? "Teaching assignment updated" : "Teaching assignment created" }); setLocation("/teaching-assignments"); }, onError: (error) => toast({ title: "Could not save teaching assignment", description: teachingAssignmentErrorMessage(error, "Could not save teaching assignment.") }) }); };
  const deleteCurrent = () => { if (!assignment || !window.confirm("Delete this teaching assignment permanently? This is a hard delete and cannot be restored.")) return; remove.mutate(assignment.id, { onSuccess: () => setLocation("/teaching-assignments"), onError: (error) => toast({ title: "Could not delete teaching assignment", description: teachingAssignmentErrorMessage(error, "Teaching assignment not found.") }) }); };
  return <><button className="back-link page-back" onClick={() => setLocation("/teaching-assignments")}><ArrowLeft size={15} />Back to Teaching assignments</button><PageHeader eyebrow={editing ? "Edit assignment" : "New assignment"} title={editing ? "Edit teaching assignment" : "Add teaching assignment"} description="Keep Subject and Section selections connected to the selected Class." /><form className="form-card" onSubmit={form.handleSubmit(submit, () => toast({ title: "Check the form", description: "Select all assignment relationships." }))}><div className="form-grid"><SelectField form={form} name="staffId" label="Staff" options={(staff.data || []).map((member) => [member.id, `${member.firstName} ${member.lastName}`])} disabled={editing} /><SelectField form={form} name="classId" label="Class" options={(classes.data || []).map((schoolClass) => [schoolClass.id, schoolClass.name])} /><SelectField form={form} name="subjectId" label="Subject" options={(subjects.data || []).map((subject) => [subject.id, subject.name])} /><SelectField form={form} name="sectionId" label="Section" options={(sections.data || []).map((section) => [section.id, section.name])} /></div><div className="form-actions"><AppButton type="button" variant="ghost" onClick={() => setLocation("/teaching-assignments")}>Cancel</AppButton>{editing && <AppButton type="button" variant="danger" onClick={deleteCurrent}>Delete</AppButton>}<AppButton type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : editing ? "Save changes" : "Create assignment"}<ArrowRight size={16} /></AppButton></div></form></>;
}

